### ISSUE TITLE
Installation issue on Linux cluster

### ISSUE THREAD

**Issue by ksmetz** [EricSDavis/mariner#5]
I am trying to install mariner as a personal R package on a Linux HPC cluster at my institution. However, building the package (either with `remotes` or `devtools`) failed with the following error:
```
Error in parse(outFile) : 
  /lscratch/61170698/Rtmp8sGpgc/R.INSTALL8ca92c9f7902/mariner/R/methods-changePixelRes.R:50:29: unexpected input
49:         strsplit(pixels, "-") |>
50:         do.call(rbind, args=_
                                ^
ERROR: unable to collate and parse R files for package 'mariner'
```

According to other folks who have seen this error, it appears to be caused by open braces, although it does not accurately report which file the open braces are occurring in.
- https://stackoverflow.com/questions/62364853/error-in-parseoutfile-unexpected-end-of-input-bug-in-package-install-and
- https://github.com/r-lib/remotes/issues/507

Strangely I did not have this issue when installing to my local machine (Mac OSX), however I did have to use `remotes::install_local` with the .ZIP file because `install_github` stalled out. Attempting this approach on the cluster caused the same `parse(outFile)` error.

I will be looking into this issue to see if it something specific to my cluster, but thought I would post in case anyone else experiences this issue!

**Comment by EricSDavis** [comment]
Hi Katie, thanks for posting! I have seen this error before as well when helping others install this package. I can't remember exactly what the issue was, but I suspect it has to do with the R version used. I think passing an argument with the pipe operator and using it with a named argument with the "_" is a newer feature and is used in that function which might be causing the error. Is your R version at least 4.2.0?

**Comment by ksmetz** [comment]
Hi Eric, thanks for the super quick response! I had been trying R 4.2.2 before, but actually since you mention it I had changed to 4.1.2 (because that is the R version for which we were able to successfully install strawr for). I will discuss with the HPC folks here and see if there is a way that we can get strawr working with R 4.2.X, and hopefully that will fix it!
